//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Answer_Code { get; set; }
        public Nullable<int> Question_Code { get; set; }
        public string Answer_Content1 { get; set; }
        public string Answer_Content2 { get; set; }
        public string Answer_Content3 { get; set; }
        public string Answer_Content4 { get; set; }
        public string Answer_Correct { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
