//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class English_Learning_WebsiteEntities2 : DbContext
    {
        public English_Learning_WebsiteEntities2()
            : base("name=English_Learning_WebsiteEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quiz_Detail> Quiz_Detail { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<Userz> Userzs { get; set; }
        public virtual DbSet<Vocabulary> Vocabularies { get; set; }
        public virtual DbSet<Vocabulary_Type> Vocabulary_Type { get; set; }
    }
}
