//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            this.Quiz_Detail = new HashSet<Quiz_Detail>();
        }
    
        public int Quiz_Code { get; set; }
        public string Quiz_Name { get; set; }
        public string Quiz_Content { get; set; }
        public string Quiz_AnswerOne { get; set; }
        public string Quiz_AnswerTwo { get; set; }
        public string Quiz_AnswerThree { get; set; }
        public string Quiz_AnswerFour { get; set; }
        public string Quiz_AnswerFive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz_Detail> Quiz_Detail { get; set; }
    }
}
