//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Detail
    {
        public int User_Code { get; set; }
        public int Vocabulary_Type_Code { get; set; }
        public Nullable<double> Quiz_Score { get; set; }
    
        public virtual Userz Userz { get; set; }
        public virtual Vocabulary_Type Vocabulary_Type { get; set; }
    }
}
