//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int Story_Code { get; set; }
        public string Story_Name { get; set; }
        public string Story_Content_EN { get; set; }
        public string Story_Content_VN { get; set; }
        public string Story_Audio { get; set; }
        public Nullable<int> Story_View { get; set; }
        public string Story_banner { get; set; }
        public string Story_image { get; set; }
        public Nullable<int> Userz_Code { get; set; }
    
        public virtual Userz Userz { get; set; }
    }
}
