//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Detail
    {
        public int Test_Code { get; set; }
        public Nullable<double> Test_Score { get; set; }
        public int User_Code { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
