//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int Vocabulary_Code { get; set; }
        public string Vocabulary_English { get; set; }
        public string Vocabulary_Vietnamese { get; set; }
        public string Vocabulary_Pronunciation { get; set; }
        public string Vocabulary_Image { get; set; }
        public Nullable<int> Vocabulary_Type_Code { get; set; }
    
        public virtual Vocabulary_Type Vocabulary_Type { get; set; }
    }
}
